import { LLMService } from './llm';
import { sendEmail } from '../tools/implementations/email-tools';
import { prisma } from '@/lib/prisma';

interface CalendarEvent {
  summary: string;
  description?: string | null;
  startDateTime: Date;
  endDateTime: Date;
  location?: string | null;
  attendees: any[];
  organizer?: any;
}

export class CalendarEmailNotificationService {
  private llmService: LLMService;

  constructor() {
    this.llmService = new LLMService();
  }

  async extractEmailFromAttendees(attendees: any[]): Promise<string[]> {
    if (!attendees || !Array.isArray(attendees)) return [];
    
    return attendees
      .filter(attendee => attendee.email && attendee.email !== process.env.GOOGLE_USER_EMAIL)
      .map(attendee => attendee.email);
  }

  async generateAppointmentEmail(event: CalendarEvent, emailType: 'created' | 'updated' = 'created'): Promise<{ subject: string; body: string }> {
    const formatDateTime = (date: Date) => {
      return date.toLocaleDateString('en-US', {
        weekday: 'long',
        year: 'numeric',
        month: 'long',
        day: 'numeric',
        hour: 'numeric',
        minute: '2-digit',
        timeZoneName: 'short'
      });
    };

    const startTime = formatDateTime(event.startDateTime);
    const endTime = formatDateTime(event.endDateTime);
    const duration = Math.round((event.endDateTime.getTime() - event.startDateTime.getTime()) / (1000 * 60));

    const promptContext = `
Generate a professional email notification for a calendar appointment that was ${emailType}.

Appointment Details:
- Title: ${event.summary}
- Description: ${event.description || 'No description provided'}
- Start Time: ${startTime}
- End Time: ${endTime}
- Duration: ${duration} minutes
- Location: ${event.location || 'Video Call'}

Please generate:
1. A subject line (keep it under 50 characters)
2. A professional email body that includes all the important details

The email should be:
- Professional and friendly in tone
- Include all the meeting details clearly
- Mention how to join if it's a video call
- Include a brief note that this was automatically generated
- Use HTML formatting for better presentation

Format your response as JSON:
{
  "subject": "Your subject line here",
  "body": "Your HTML email body here"
}`;

    try {
      const llmResponse = await this.llmService.generateSimpleText(promptContext);
      
      // Try to parse the JSON response
      let parsedResponse;
      try {
        parsedResponse = JSON.parse(llmResponse);
      } catch (parseError) {
        // Fallback if LLM doesn't return valid JSON
        console.warn('LLM did not return valid JSON, using fallback');
        parsedResponse = {
          subject: `${emailType === 'created' ? 'New' : 'Updated'} Meeting: ${event.summary}`,
          body: this.generateFallbackEmailBody(event, emailType)
        };
      }

      return {
        subject: parsedResponse.subject || `Meeting: ${event.summary}`,
        body: parsedResponse.body || this.generateFallbackEmailBody(event, emailType)
      };
    } catch (error) {
      console.error('Error generating email with LLM:', error);
      return {
        subject: `${emailType === 'created' ? 'New' : 'Updated'} Meeting: ${event.summary}`,
        body: this.generateFallbackEmailBody(event, emailType)
      };
    }
  }

  private generateFallbackEmailBody(event: CalendarEvent, emailType: 'created' | 'updated'): string {
    const formatDateTime = (date: Date) => {
      return date.toLocaleDateString('en-US', {
        weekday: 'long',
        year: 'numeric',
        month: 'long',
        day: 'numeric',
        hour: 'numeric',
        minute: '2-digit',
        timeZoneName: 'short'
      });
    };

    return `
<html>
<body>
  <h2>Meeting ${emailType === 'created' ? 'Invitation' : 'Update'}</h2>
  
  <p>You have been ${emailType === 'created' ? 'invited to' : 'notified of an update to'} the following meeting:</p>
  
  <div style="background-color: #f5f5f5; padding: 20px; border-radius: 5px; margin: 20px 0;">
    <h3>${event.summary}</h3>
    <p><strong>Date & Time:</strong> ${formatDateTime(event.startDateTime)} - ${formatDateTime(event.endDateTime)}</p>
    <p><strong>Location:</strong> ${event.location || 'Video Call'}</p>
    ${event.description ? `<p><strong>Description:</strong> ${event.description}</p>` : ''}
  </div>
  
  <p>Please mark your calendar accordingly.</p>
  
  <hr style="margin: 30px 0;">
  <p style="font-size: 12px; color: #666;">
    This email was automatically generated by your AI assistant when the calendar event was ${emailType}.
  </p>
</body>
</html>`;
  }

  async sendAppointmentNotifications(
    userId: string, 
    event: CalendarEvent, 
    emailType: 'created' | 'updated' = 'created'
  ): Promise<{ success: boolean; sentEmails: string[]; errors: string[] }> {
    const recipientEmails = await this.extractEmailFromAttendees(event.attendees);
    
    if (recipientEmails.length === 0) {
      console.log('No recipient emails found for calendar event notification');
      return { success: true, sentEmails: [], errors: [] };
    }

    const emailContent = await this.generateAppointmentEmail(event, emailType);
    const sentEmails: string[] = [];
    const errors: string[] = [];

    for (const email of recipientEmails) {
      try {
        console.log(`Sending ${emailType} notification to ${email} for event: ${event.summary}`);
        
        await sendEmail(
          {
            to: email,
            subject: emailContent.subject,
            body: emailContent.body
          },
          userId
        );

        sentEmails.push(email);
        console.log(`✅ Successfully sent ${emailType} notification to ${email}`);
      } catch (error) {
        const errorMsg = `Failed to send email to ${email}: ${error instanceof Error ? error.message : 'Unknown error'}`;
        console.error(errorMsg);
        errors.push(errorMsg);
      }
    }

    return {
      success: errors.length === 0,
      sentEmails,
      errors
    };
  }
}